### PR TITLE
updated contract files esp. oreotoken.sol, node_modules, config file …

### PR DESCRIPTION
**Pull request by bobeu**
Please check files

### CODE REVIEW

**Review by favor78 — APPROVED** [review]

**Review by favor78 — APPROVED** [review]
Good

**Review by favor78 — APPROVED** [review]
Nice

**Review by ahmadou5 — APPROVED** [review]

**Review by frank-coder — APPROVED** [review]
Good Work

**Review by calebjesusegun — APPROVED** [review]
I'm okay with the updated contract files...This is great

**Review by epikoder — APPROVED** [review]
Good

**Comment by justinokpuandco** [comment]
Good

**Pull request closed without merging**
