### PR TITLE
Update Oreo Token.sol

### PR DESCRIPTION
**Pull request by ahmadou5**
Token symbol updated from oreo to OREO

### CODE REVIEW

**Review by bobeu — APPROVED** [review]

**Review by frank-coder — APPROVED** [review]
Looks good

**Comment by ahmadou5** [comment]
Thanks bro

**Review by myquery — APPROVED** [review]

**Review by ahmadou5 — COMMENTED** [review]
Cool

**Review by myquery — APPROVED** [review]

**Comment by myquery** [comment]
this contract can't ne merged, reason why the workflow rejects it we need to verify and correct

**Comment by ahmadou5** [comment]
I updated couples things down the contract....for the governance functions some. Reverts are with cake and i change them to Oreo ....

**Pull request closed without merging**
